Repository Ces-Intern-2024/House-Sale-FE, pull requests merged in 2024-02, with the labels that each got.

#18 feat: seller dashboard
  src/App.tsx
  src/components/DetailsImageList/DetailsImageList.module.scss
  src/components/DetailsImageList/DetailsImageList.tsx
  src/components/MenuBar/MenuBar.module.scss
  src/components/MenuBar/MenuBar.tsx
  src/components/MultiCarousel/MuitiCarousel.tsx
  src/components/MultiCarousel/MultiCarousel.module.scss
  src/components/Profile/SellerProfile.module.scss
  src/components/Profile/SellerProfile.tsx
  src/components/SearchBar/TextSearchBar.module.scss
  src/components/layouts/SellerLayout/SellerLayout.module.scss
  src/components/layouts/SellerLayout/SellerLayout.tsx
  src/pages/DetailPage/DetailPage.module.scss
  src/pages/DetailPage/DetailPage.tsx
  src/pages/SellerPage/SellerPage.tsx
  src/redux/reducers/reducer.ts
Labels: feature

#20 feat: seller dashboard
  src/components/Profile/SellerProfile.module.scss
  src/components/Profile/SellerProfile.tsx
Labels: feature

#19 feat: create table property for seller
  src/App.css
  src/components/BannerWelcome/BannerWelcome.module.scss
  src/components/ContactUs/ContactUs.module.scss
  src/components/ContactUs/ContactUs.tsx
  src/components/Credit/Credit.module.scss
  src/components/Credit/Credit.tsx
  src/components/CustomInput/Input.module.scss
  src/components/FeaturedProperties/FeaturedProperties.tsx
  src/components/FeaturedProperties/styles.module.scss
  src/components/Footer/Footer.tsx
  src/components/Footer/styles.module.scss
  src/components/ModalProperty/ModalProperty.module.scss
  src/components/ModalProperty/ModalProperty.tsx
  src/components/TableProperty/TableProperty.module.scss
  src/components/TableProperty/TableProperty.tsx
  src/components/layouts/SellerLayout/SellerLayout.module.scss
  src/components/layouts/SellerLayout/SellerLayout.tsx
  src/pages/HomePage/HomePage.module.scss
  src/pages/HomePage/HomePage.tsx
  src/pages/SellerPage/SellerPage.tsx
  src/styles/_variables.scss
  tailwind.config.js
Labels: feature

#21 feat: create modal add & edit & view property to manage
  src/components/Credit/Credit.module.scss
  src/components/ModalProperty/ModalProperty.module.scss
  src/components/ModalProperty/ModalProperty.tsx
  src/components/TableProperty/TableProperty.module.scss
  src/components/TableProperty/TableProperty.tsx
  src/types/properties.ts
  src/utils/properties.ts
Labels: feature

#22 feat: seller profile
  src/App.tsx
  src/components/Profile/SellerProfile.tsx
  src/components/layouts/SellerLayout/SellerLayout.tsx
Labels: feature

#24 feat: create login form
  package-lock.json
  package.json
  src/App.tsx
  src/components/Login/Login.tsx
  src/components/MenuBar/MenuBar.tsx
  src/index.tsx
  src/redux/reducers/authReducer.ts
  src/utils/localStorage.ts
Labels: duplicate

#26 feat: upload images list for seller in processing of adding new property
  package-lock.json
  package.json
  src/App.tsx
  src/components/BannerWelcome/BannerWelcome.module.scss
  src/components/ContactUs/ContactUs.module.scss
  src/components/DetailsImageList/DetailsImageList.tsx
  src/components/DetailsProperty/DetailsProperty.module.scss
  src/components/Footer/Footer.tsx
  src/components/Footer/styles.module.scss
  src/components/MenuBar/MenuBar.module.scss
  src/components/MenuBar/MenuBar.tsx
  src/components/ModalProperty/ModalProperty.tsx
  src/components/Properties/PropertyCard.tsx
  src/components/Properties/styles.module.scss
  src/components/SearchBar/TextSearchBar.tsx
  src/components/Slideshow/SlideShow.tsx
  src/components/TableProperty/TableProperty.module.scss
  src/components/TableProperty/TableProperty.tsx
  src/components/layouts/SellerLayout/SellerLayout.tsx
  src/index.tsx
  src/pages/HomePage/HomePage.tsx
  src/redux/action.ts
  src/redux/hooks.ts
  src/redux/reducers/homeReducer.ts
  src/redux/reducers/index.ts
  src/redux/reducers/reducer.ts
  src/redux/reducers/resizeReducer.ts
  src/redux/store.ts
  src/routes/Routes.tsx
  src/types/properties.ts
  src/utils/properties.ts
  tailwind.config.js
Labels: feature

#27 feat: upload avatar
  package.json
  src/App.tsx
  src/components/Login/Login.tsx
  src/components/MenuBar/MenuBar.tsx
  src/components/Profile/SellerProfile.module.scss
  src/components/Profile/SellerProfile.tsx
  src/components/Register/Register.tsx
  src/components/SearchBar/TextSearchBar.tsx
  src/components/layouts/SellerLayout/SellerLayout.tsx
  src/index.tsx
  src/pages/HomePage/HomePage.tsx
  src/redux/reducers/resizeSlice.ts
  src/redux/store.ts
  src/service/AvatarService.ts
  src/service/LocationService.ts
  src/service/ProfileService.ts
  src/types/user.ts
  src/types/ward.ts
Labels: feature

#28 feat: upload avatar + add some changes about css
  src/components/BannerWelcome/BannerWelcome.module.scss
  src/components/Header/Header.module.scss
  src/components/Profile/SellerProfile.tsx
  src/components/Slideshow/SlideShow.module.scss
  src/components/Slideshow/SlideShow.tsx
  src/components/layouts/CommonLayout/Layout.module.scss
  src/redux/reducers/locationReducer.ts
Labels: duplicate

#29 feat: avatar
  src/App.tsx
  src/components/Slideshow/SlideShow.tsx
  src/index.tsx
  tailwind.config.js
Labels: feature

#30 feat: creat route
  package-lock.json
  package.json
  src/App.tsx
  src/components/Header/Header.tsx
  src/components/Login/Login.tsx
  src/components/MenuBar/MenuBar.module.scss
  src/components/MenuBar/MenuBar.tsx
  src/components/MultiCarousel/MuitiCarousel.tsx
  src/components/Profile/SellerProfile.tsx
  src/components/Profile/UserProfile.module.scss
  src/components/Profile/UserProfile.tsx
  src/components/Register/Register.tsx
  src/components/SearchBar/TextSearchBar.tsx
  src/components/SearchPage/SearchPage.tsx
  src/components/Slideshow/SlideShow.tsx
  src/components/Unauthorized/Unauthorize.tsx
  src/components/layouts/AuthLayout/AuthLayout.tsx
  src/components/layouts/CommonLayout/CommonLayout.module.scss
  src/components/layouts/CommonLayout/CommonLayout.tsx
  src/components/layouts/Layouts.tsx
  src/components/layouts/SellerLayout/SellerLayout.module.scss
  src/components/layouts/SellerLayout/SellerLayout.tsx
  src/configs/app.config.ts
  src/configs/route.config/route.configs.ts
  src/hooks/useAuth.ts
  src/hooks/useAuthority.ts
  src/index.tsx
  src/redux/reducers/locationSlice.ts
  src/redux/reducers/reducer.ts
  src/redux/reducers/sessionSlice.ts
  src/redux/reducers/userSlice.ts
  src/redux/store.ts
  src/routes/AppRoute.tsx
  src/routes/AuthRoute.tsx
  src/routes/AuthorityGuard.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/PublicRoute.tsx
  src/routes/Routes.tsx
  src/service/AvatarService.ts
  src/service/AxiosInstance.tsx
  src/service/LocationService.ts
  src/service/ProfileService.ts
  src/service/RegisterService.ts
  src/types/role.ts
  src/types/routes.tsx
  src/types/token.ts
  src/types/user.ts
  src/views/Views.tsx
  tailwind.config.js
Labels: feature

#31 feat: create function add new property for seller
  src/components/BannerWelcome/BannerWelcome.module.scss
  src/components/BannerWelcome/BannerWelcome.tsx
  src/components/DetailsProperty/DetailsProperty.module.scss
  src/components/DetailsProperty/DetailsProperty.tsx
  src/components/FeaturedProperties/FeaturedProperties.tsx
  src/components/FeaturedProperties/styles.module.scss
  src/components/ModalProperty/ModalProperty.tsx
  src/components/Properties/PropertyCard.tsx
  src/components/TableProperty/TableProperty.tsx
  src/index.tsx
  src/pages/HomePage/HomePage.tsx
  src/redux/hooks.ts
  src/redux/reducers/homeReducer.ts
  src/redux/reducers/locationReducer.ts
  src/redux/reducers/locationSlice.ts
  src/redux/store.ts
  src/service/AxiosInstance.tsx
  src/types/district.ts
  src/types/properties.ts
  src/types/province.ts
  src/types/user.ts
  src/types/ward.ts
  src/utils/properties.ts
Labels: feature

#32 feat: search-page
  src/components/ChangePassword/ChangePassword.module.scss
  src/components/ChangePassword/ChangePassword.tsx
  src/components/Login/Login.tsx
  src/components/MenuBar/MenuBar.tsx
  src/components/Profile/UserProfile.module.scss
  src/components/Profile/UserProfile.tsx
  src/components/Register/Register.tsx
  src/components/SearchBar/SearchBar.module.scss
  src/components/SearchBar/SearchBar.tsx
  src/configs/route.config/route.configs.ts
  src/service/AxiosInstance.tsx
  src/service/ProfileService.ts
  src/service/RegisterService.ts
  src/types/user.ts
  tailwind.config.js
Labels: enhancement

#36 feat: Completed apply api add-update-delete property for seller
  src/components/BannerValue/BannerValue.module.scss
  src/components/ModalProperty/ModalProperty.module.scss
  src/components/ModalProperty/ModalProperty.tsx
  src/components/TableProperty/TableProperty.tsx
  src/redux/reducers/homeReducer.ts
  src/redux/reducers/locationReducer.ts
  tailwind.config.js
Labels: enhancement

#38 feat: fix scss to deploy
  package-lock.json
  package.json
  src/components/Profile/UserProfile.tsx
  src/components/Register/Register.tsx
  src/components/SearchBar/CustomSelect.tsx
  src/components/SearchBar/SearchBar.module.scss
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/TextSearchBar.tsx
  src/components/layouts/Layouts.tsx
  src/configs/route.config/route.configs.ts
  src/pages/SearchPage/SearchPage.tsx
  src/redux/store.ts
  src/service/SearchService.tsx
Labels: feature

#42 feat: create component wishlist. v2-update wishlist
  package-lock.json
  package.json
  src/assets/images/logo.png
  src/components/ChangePassword/ChangePassword.tsx
  src/components/Credit/Credit.tsx
  src/components/Login/Login.module.scss
  src/components/Login/Login.tsx
  src/components/MenuBar/MenuBar.tsx
  src/components/ModalProperty/ModalProperty.tsx
  src/components/Properties/PropertyCard.tsx
  src/components/Register/Register.module.scss
  src/components/Register/Register.tsx
  src/components/TableProperty/TableProperty.tsx
  src/index.tsx
  src/service/SellerService.ts
  src/types/user.ts
  src/utils/commonFunctions.ts
Labels: enhancement

#43 feat: update API for credit component
  src/components/Credit/Credit.module.scss
  src/components/Credit/Credit.tsx
  src/components/Profile/UserProfile.tsx
  src/components/Properties/PropertyCard.tsx
  src/components/TableProperty/TableProperty.tsx
  src/types/historyTransaction.ts
  src/utils/commonFunctions.ts
Labels: enhancement
