Repository Ces-Intern-2024/House-Sale-FE, pull requests merged in 2024-03, with the labels that each got.

#45 feat: feedback component and fix search page -> Dat: update try catch…
  .eslintrc.js
  src/App.css
  src/App.tsx
  src/components/Credit/Credit.module.scss
  src/components/Credit/Credit.tsx
  src/components/FeaturedProperties/FeaturedProperties.tsx
  src/components/Login/Login.tsx
  src/components/ModalProperty/ModalProperty.tsx
  src/components/ProgressCard/ProgressCard.tsx
  src/components/Properties/PropertyCard.tsx
  src/components/TableProperty/TableProperty.module.scss
  src/components/TableProperty/TableProperty.tsx
  src/components/layouts/AdminLayout/AdminLayout.module.scss
  src/components/layouts/AdminLayout/AdminLayout.tsx
  src/components/layouts/Layouts.tsx
  src/components/layouts/SellerLayout/SellerLayout.module.scss
  src/configs/app.config.ts
  src/configs/route.config/route.configs.ts
  src/constants/codeResponse.ts
  src/index.css
  src/pages/AdminDashboardPage/AdminDashboardPage.tsx
  src/pages/AdminPropertyPage/AdminPropertyPage.tsx
  src/pages/FeedbackPage/FeedbackPage.tsx
  src/pages/HomePage/HomePage.tsx
  src/service/PropertyService.ts
  src/service/SearchService.tsx
  src/service/SellerService.ts
  src/utils/commonFunctions.ts
  tailwind.config.js
Labels: enhancement

#46 feat: contact seller
  src/components/ContactUs/ContactUs.module.scss
  src/components/ContactUs/ContactUs.tsx
  src/components/DetailsImageList/DetailsImageList.module.scss
  src/components/DetailsImageList/DetailsImageList.tsx
  src/components/DetailsProperty/DetailsProperty.module.scss
  src/components/DetailsProperty/DetailsProperty.tsx
  src/components/MenuBar/CollapseMenuItem.tsx
  src/components/MenuBar/MenuBar.module.scss
  src/components/MenuBar/MenuBar.tsx
  src/components/MultiCarousel/MuitiCarousel.tsx
  src/components/MultiCarousel/MultiCarousel.tsx
  src/components/Profile/UserProfile.tsx
  src/components/Register/Register.tsx
  src/components/SearchBar/SearchComponent.module.scss
  src/components/SearchBar/SearchComponent.tsx
  src/components/Slideshow/SlideShow.module.scss
  src/components/Slideshow/SlideShow.tsx
  src/components/layouts/Layouts.tsx
  src/configs/navigation.config/navigation.configs.ts
  src/configs/route.config/route.configs.tsx
  src/constants/layout.constant.ts
  src/hooks/useAuthority.ts
  src/pages/DetailPage/DetailPage.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/routes/PublicRoute.tsx
  src/service/ContactService.ts
  src/service/PropertyService.ts
  src/service/SearchService.ts
Labels: feature

#49 fix: update loading wishlist button and redefine rows and cols in search page
  src/components/MenuBar/CollapseMenuItem.tsx
  src/components/MenuBar/MenuBar.tsx
  src/components/Properties/PropertyCard.tsx
  src/components/SearchBar/CustomSelect.tsx
  src/components/SearchBar/SearchComponent.tsx
  src/constants/numOfReturnElements.constant.ts
  src/pages/DetailPage/DetailPage.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/service/SearchService.ts
Labels: Bugfix

#47 feat: create template and apply api for admin to manage property
  src/App.tsx
  src/components/Credit/Credit.module.scss
  src/components/Credit/Credit.tsx
  src/components/CustomButton/ButtonCustom.tsx
  src/components/FeaturedProperties/FeaturedProperties.tsx
  src/components/Login/Login.tsx
  src/components/MenuBar/MenuBar.tsx
  src/components/ModalProperty/ModalProperty.tsx
  src/components/MultiCarousel/MultiCarousel.tsx
  src/components/SearchBar/CustomSelect.tsx
  src/components/TableProperty/TableProperty.module.scss
  src/components/TableProperty/TableProperty.tsx
  src/components/TableProperty/TablePropertyAdmin.tsx
  src/components/layouts/AdminLayout/AdminLayout.tsx
  src/components/layouts/SellerLayout/SellerLayout.tsx
  src/configs/route.config/route.configs.tsx
  src/constants/statusProperty.ts
  src/index.tsx
  src/pages/AboutUsPage/AboutUsPage.tsx
  src/pages/AdminPropertyPage/AdminPropertyPage.tsx
  src/pages/DetailPage/DetailPage.tsx
  src/pages/HomePage/HomePage.tsx
  src/redux/hooks.ts
  src/redux/reducers/authReducer.ts
  src/redux/reducers/categorySlice.ts
  src/redux/reducers/featureSlice.ts
  src/redux/reducers/homeReducer.ts
  src/redux/reducers/locationReducer.ts
  src/redux/reducers/resizeSlice.ts
  src/redux/store.ts
  src/routes/AppRoute.tsx
  src/service/AdminService.ts
  src/service/AxiosInstance.tsx
  src/service/PropertyService.ts
  src/service/SearchService.ts
  src/service/SellerService.ts
  src/types/properties.ts
  src/types/searchProps.ts
  src/types/user.ts
  src/utils/commonFunctions.ts
  src/utils/properties.ts
  tailwind.config.js
Labels: feature

#51 feat: add template wishlist
  .eslintrc.js
  src/components/Credit/Credit.tsx
  src/components/FeaturedProperties/FeaturedProperties.tsx
  src/components/FeaturedProperties/styles.module.scss
  src/components/Login/Login.tsx
  src/components/ModalProperty/ModalProperty.tsx
  src/components/MultiCarousel/MultiCarousel.module.scss
  src/components/MultiCarousel/MultiCarousel.tsx
  src/components/Properties/PropertyCard.tsx
  src/components/Properties/styles.module.scss
  src/components/SearchBar/SearchComponent.tsx
  src/components/TableProperty/TableProperty.module.scss
  src/components/TableProperty/TableProperty.tsx
  src/components/TableProperty/TablePropertyAdmin.tsx
  src/components/layouts/AdminLayout/AdminLayout.tsx
  src/configs/route.config/route.configs.tsx
  src/pages/AdminManageUserPage/AdminManageUserPage.tsx
  src/pages/DetailPage/DetailPage.tsx
  src/pages/HomePage/HomePage.module.scss
  src/pages/HomePage/HomePage.tsx
  src/redux/reducers/homeSlice.ts
  src/redux/store.ts
  src/service/AdminService.ts
  src/service/SearchService.ts
  src/service/SellerService.ts
  src/types/historyTransaction.ts
  tailwind.config.js
Labels: feature

#52 feat: create transaction and transaction history
  .env
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/components/Credit/Credit.tsx
  src/components/Login/Login.tsx
  src/components/MenuBar/MenuBar.tsx
  src/components/ModalProperty/ModalProperty.tsx
  src/components/Profile/UserProfile.tsx
  src/components/SearchBar/SearchComponent.tsx
  src/components/TableProperty/TableProperty.tsx
  src/components/Transaction/CheckoutForm.tsx
  src/components/Transaction/CreditComponent.tsx
  src/components/Transaction/ExchangePolicy.tsx
  src/components/Transaction/Transaction.module.scss
  src/components/Transaction/TransactionComponent.tsx
  src/components/Transaction/TransactionHistory.tsx
  src/components/layouts/SellerLayout/SellerLayout.tsx
  src/configs/route.config/route.configs.tsx
  src/constants/credit.constant.ts
  src/constants/stripe.constant.ts
  src/index.tsx
  src/pages/SellerPage/SellerPage.tsx
  src/pages/TransactionPage/TransactionPage.tsx
  src/service/AxiosInstance.tsx
  src/service/SearchService.ts
  src/service/StripeService.ts
  src/service/TransactionService.ts
  src/utils/commonFunctions.ts
Labels: feature

#55 feat: add template user detail and apply api
  .env
  package-lock.json
  package.json
  src/assets/images/user.png
  src/components/ModalManageUser/ModalManageUser.module.scss
  src/components/ModalManageUser/ModalManageUser.tsx
  src/components/ModalProperty/ModalProperty.module.scss
  src/components/ModalProperty/ModalProperty.tsx
  src/components/Properties/PropertyCard.tsx
  src/components/TableProperty/TableProperty.tsx
  src/components/TableProperty/TablePropertyAdmin.tsx
  src/components/TableUser/TableUser.module.scss
  src/components/TableUser/TableUser.tsx
  src/components/Transaction/TransactionComponent.tsx
  src/service/AdminService.ts
  src/types/user.ts
Labels: feature

#54 fix: transation layout
  .DS_Store
  src/.DS_Store
  src/components/.DS_Store
  src/components/Profile/UserProfile.module.scss
  src/components/Profile/UserProfile.tsx
  src/components/Transaction/CheckoutForm.tsx
  src/components/Transaction/Transaction.module.scss
  src/components/Transaction/TransactionComponent.tsx
  src/components/Transaction/TransactionHistory.tsx
  src/components/layouts/SellerLayout/SellerLayout.tsx
  src/configs/route.config/route.configs.tsx
  src/pages/SellerPage/SellerPage.tsx
  src/service/SellerService.ts
  src/service/StripeService.ts
  src/utils/commonFunctions.ts
Labels: enhancement, Bugfix

#56 fix: reset the field when click clear filter and update icon sort by …
  .env
  src/components/ModalProperty/ModalProperty.module.scss
  src/components/ModalProperty/ModalProperty.tsx
  src/components/TableProperty/TablePropertyAdmin.tsx
Labels: Bugfix

#58 feat: add multiple select to delele all property and fix re-enable pr…
  src/components/ModalManageUser/ModalManageUser.tsx
  src/components/ModalProperty/ModalProperty.module.scss
  src/components/ModalProperty/ModalProperty.tsx
  src/components/TableProperty/TableProperty.module.scss
  src/components/TableProperty/TableProperty.tsx
  src/components/TableProperty/TablePropertyAdmin.tsx
  src/components/TableUser/TableUser.tsx
  src/constants/colorConstant.ts
  src/pages/FeedbackPage/FeedbackPage.tsx
  src/service/AdminService.ts
  src/service/PackageService.ts
  src/service/SellerService.ts
  src/styles/_variables.scss
  src/types/packageService.ts
  src/types/properties.ts
  src/utils/properties.ts
  tailwind.config.js
Labels: feature

#57 feat: admin transaction
  src/components/SearchBar/SearchComponent.tsx
  src/components/TableTransaction/TableTransaction.module.scss
  src/components/TableTransaction/TableTransaction.tsx
  src/components/Transaction/TransactionHistory.tsx
  src/components/layouts/AdminLayout/AdminLayout.tsx
  src/configs/route.config/route.configs.tsx
  src/constants/color.ts
  src/pages/AdminTransactionPage/AdminTransactionPage.tsx
  src/service/AdminService.ts
  src/utils/commonFunctions.ts
Labels: feature

#60 feat: handle updating status of property for seller
  src/components/TableProperty/TableProperty.module.scss
  src/components/TableProperty/TableProperty.tsx
  src/components/TableTransaction/TableTransaction.tsx
  src/constants/color.ts
  src/constants/colorConstant.ts
  src/service/SellerService.ts
Labels: feature

#62 feat: create countdown timer for displaying effective datetime
  src/components/TableProperty/TableProperty.tsx
  src/pages/SellerPage/SellerPage.tsx
Labels: feature

#64 fix: search bar and carousel component
  src/components/DetailsImageList/DetailsImageList.module.scss
  src/components/DetailsImageList/DetailsImageList.tsx
  src/components/SearchBar/SearchComponent.tsx
  src/components/SearchBar/TextSearchBar.module.scss
  src/components/SearchBar/TextSearchBar.tsx
  src/components/Transaction/TransactionHistory.tsx
  src/constants/category.constant.ts
  src/pages/DetailPage/DetailPage.tsx
  tailwind.config.js
Labels: Bugfix

#63 fix: button delete property, clear filter, border select
  .env
  package-lock.json
  package.json
  src/assets/images/BannerWelcomeImage.png
  src/assets/images/BannerWelcomeImage1.png
  src/assets/images/BannerWelcomeImage2.png
  src/assets/images/BannerWelcomeImage4.png
  src/assets/images/area.png
  src/assets/images/avatar.jpg
  src/assets/images/bannerWelcomeX.jpg
  src/assets/images/bannerWelcomeX1.jpg
  src/assets/images/bannerWelcomeX2.jpg
  src/assets/images/bed.png
  src/assets/images/room.png
  src/assets/images/stair.png
  src/components/ContactUs/ContactUs.tsx
  src/components/ConversionRate/ConversionRateComponent.tsx
  src/components/DetailsImageList/DetailsImageList.module.scss
  src/components/DetailsProperty/DetailsProperty.tsx
  src/components/Footer/styles.module.scss
  src/components/Login/Login.module.scss
  src/components/Login/Login.tsx
  src/components/ModalProperty/ModalProperty.tsx
  src/components/Properties/PropertyCard.tsx
  src/components/Properties/styles.module.scss
  src/components/TableProperty/TableProperty.module.scss
  src/components/TableProperty/TableProperty.tsx
  src/components/TableProperty/TablePropertyAdmin.tsx
  src/components/TableTransaction/TableTransaction.tsx
  src/components/TableUser/TableUser.module.scss
  src/components/TableUser/TableUser.tsx
  src/components/Transaction/Transaction.module.scss
  src/components/layouts/AuthLayout/AuthLayout.module.scss
  src/configs/navigation.config/navigation.configs.ts
  src/constants/actions.constant.ts
  src/constants/codeResponse.constant.ts
  src/constants/color.constant.ts
  src/constants/statusProperty.constant.ts
  src/index.tsx
  src/pages/FeedbackPage/FeedbackPage.tsx
  src/service/AdminService.ts
  src/service/AxiosInstance.tsx
  src/service/PropertyService.ts
  src/utils/commonFunctions.ts
  tailwind.config.js
Labels: Bugfix

#66 fix: button delete property, clear filter, border select
  src/components/BannerWelcome/BannerWelcome.module.scss
  src/components/Credit/Credit.tsx
  src/components/DetailsImageList/DetailsImageList.module.scss
  src/components/DetailsProperty/DetailsProperty.tsx
  src/components/Footer/styles.module.scss
  src/components/Map/Map.module.scss
  src/components/MenuBar/MenuBar.module.scss
  src/components/MenuBar/MenuBar.tsx
  src/components/ModalPackageService/ModalPackageService.module.scss
  src/components/ModalPackageService/ModalPackageService.tsx
  src/components/ModalProperty/ModalProperty.module.scss
  src/components/ModalProperty/ModalProperty.tsx
  src/components/MultiCarousel/MultiCarousel.tsx
  src/components/Properties/PropertyCard.tsx
  src/components/Properties/styles.module.scss
  src/components/SearchBar/SearchComponent.tsx
  src/components/SearchBar/TextSearchBar.module.scss
  src/components/SearchBar/TextSearchBar.tsx
  src/components/TableProperty/TableProperty.module.scss
  src/components/TableProperty/TableProperty.tsx
  src/components/TableProperty/TablePropertyAdmin.tsx
  src/components/TableUser/TableUser.module.scss
  src/components/TableUser/TableUser.tsx
  src/components/Transaction/CreditComponent.tsx
  src/components/Transaction/TransactionHistory.tsx
  src/components/layouts/AdminLayout/AdminLayout.module.scss
  src/components/layouts/AdminLayout/AdminLayout.tsx
  src/components/layouts/SellerLayout/SellerLayout.module.scss
  src/components/layouts/SellerLayout/SellerLayout.tsx
  src/constants/actions.constant.ts
  src/constants/color.constant.ts
  src/index.css
  src/pages/SellerPage/SellerPage.tsx
  src/service/SellerService.ts
  tailwind.config.js
Labels: Bugfix

#65 feat: transaction history page and change search component route
  .DS_Store
  package-lock.json
  package.json
  src/.DS_Store
  src/components/ContactUs/ContactUs.tsx
  src/components/DetailsImageList/DetailsImageList.tsx
  src/components/DetailsProperty/DetailsProperty.tsx
  src/components/MenuBar/CollapseMenuItem.tsx
  src/components/Properties/PropertyCard.tsx
  src/components/SearchBar/SearchComponent.tsx
  src/components/SearchBar/TextSearchBar.tsx
  src/components/Slideshow/SlideShow.tsx
  src/components/TableProperty/TableProperty.tsx
  src/components/TableTransaction/TableTransaction.tsx
  src/components/Transaction/TransactionHistory.tsx
  src/components/layouts/Layouts.tsx
  src/components/layouts/SellerLayout/SellerLayout.tsx
  src/configs/route.config/route.configs.tsx
  src/pages/AdminTransactionPage/AdminTransactionPage.tsx
  src/pages/SellerPage/SellerPage.tsx
  src/pages/SellerTransactionHistory/SellerTransactionHistory.tsx
  src/service/SearchService.ts
  src/service/TransactionService.ts
  src/utils/commonFunctions.ts
  tailwind.config.js
Labels: feature, Bugfix

#67 feat: create google maps component
  .env
  package-lock.json
  package.json
  src/components/ContactUs/ContactUs.module.scss
  src/components/DetailsProperty/DetailsProperty.module.scss
  src/components/DetailsProperty/DetailsProperty.tsx
  src/components/FeaturedProperties/FeaturedProperties.tsx
  src/components/FeaturedProperties/styles.module.scss
  src/components/Map/Map.tsx
  src/components/ModalManageUser/ModalManageUser.tsx
  src/components/Properties/PropertyCard.tsx
  src/components/Properties/styles.module.scss
  src/components/Register/Register.module.scss
  src/components/SearchBar/TextSearchBar.module.scss
  src/components/SearchBar/TextSearchBar.tsx
  src/components/TableProperty/TableProperty.tsx
  src/components/TableUser/TableUser.tsx
  src/components/layouts/AdminLayout/AdminLayout.tsx
  src/components/layouts/SellerLayout/SellerLayout.tsx
  src/constants/category.constant.ts
  src/constants/google.constant.ts
  src/index.tsx
  src/pages/DetailPage/DetailPage.tsx
  src/service/AdminService.ts
  src/service/MapsService.ts
  src/types/properties.ts
  tailwind.config.js
Labels: feature

#70 feat: disable property from wishlist and add event beforeunload
  package-lock.json
  package.json
  src/components/ModalProperty/ModalProperty.tsx
  src/components/MultiCarousel/MultiCarousel.tsx
  src/components/Properties/PropertyCard.tsx
  src/components/Properties/styles.module.scss
  src/components/TableProperty/TableProperty.tsx
Labels: feature

#72 feat: create template report for admin
  package-lock.json
  package.json
  src/components/Charts/LineChart.tsx
  src/components/Charts/PieChart.css
  src/components/Charts/PieChart.tsx
  src/components/Login/Login.tsx
  src/pages/AdminDashboardPage/AdminDashboardPage.tsx
Labels: feature

#71 feat: maintenance component
  src/App.tsx
  src/components/ChangePassword/ChangePassword.tsx
  src/components/Credit/Credit.tsx
  src/components/DetailsImageList/DetailsImageList.module.scss
  src/components/DetailsImageList/DetailsImageList.tsx
  src/components/LoadingPage/LoadingPage.tsx
  src/components/Maintenance/MaintenanceComponent.module.scss
  src/components/Maintenance/MaintenanceComponent.tsx
  src/components/MenuBar/MenuBar.module.scss
  src/components/MenuBar/MenuBar.tsx
  src/components/Profile/UserProfile.tsx
  src/components/Properties/PropertyCard.tsx
  src/components/TableProperty/TableProperty.tsx
  src/components/TableTransaction/TableTransaction.tsx
  src/components/Transaction/CheckoutForm.tsx
  src/components/Transaction/CreditComponent.tsx
  src/components/Transaction/TransactionHistory.tsx
  src/components/UnderMaintenance/UnderMaintenance.tsx
  src/components/layouts/AdminLayout/AdminLayout.tsx
  src/components/layouts/Layouts.tsx
  src/configs/route.config/route.configs.tsx
  src/constants/codeResponse.constant.ts
  src/pages/SellerPage/SellerPage.tsx
  src/service/MaintenanceService.ts
  src/service/SellerService.ts
  src/service/TransactionService.ts
  src/types/historyTransaction.ts
  src/views/Views.tsx
  tailwind.config.js
Labels: feature

#73 fix: check balance before displaying addNewProperty component
  src/components/Charts/LineChart.tsx
  src/components/Maintenance/MaintenanceComponent.tsx
  src/components/MenuBar/MenuBar.tsx
  src/components/Profile/UserProfile.tsx
  src/components/Properties/PropertyCard.tsx
  src/components/TableProperty/TableProperty.tsx
  src/components/Transaction/CreditComponent.tsx
  src/components/UnderMaintenance/UnderMaintenance.tsx
  src/pages/SellerPage/SellerPage.tsx
Labels: Bugfix

#76 feat: add line and bar charts to seller dashboard
  src/components/Charts/BarChart.tsx
  src/components/Charts/DoubleLineChart.tsx
  src/components/Charts/LineChart.tsx
  src/components/Charts/PieChart.css
  src/components/ProgressCard/ProgressCard.tsx
  src/pages/SellerReportPage/SellerReportPage.tsx
  src/service/SellerService.ts
Labels: feature
