Repository Ces-Intern-2024/House-Sale-FE, pull requests merged in 2024-04, with the labels that each got.

#78 feat: change line chart and add calendar for date range
  src/components/Charts/BarChart.tsx
  src/components/Charts/DoubleLineChart.tsx
  src/components/Charts/LineChart.tsx
  src/components/Charts/PieChart.tsx
  src/components/ConversionRate/ConversionRateComponent.tsx
  src/components/Maintenance/MaintenanceComponent.tsx
  src/components/Profile/UserProfile.module.scss
  src/components/ProgressCard/BalanceViewer.tsx
  src/components/TableTransaction/TableServiceTransaction.tsx
  src/components/TableTransaction/TableTransaction.tsx
  src/components/TableUser/TableUser.tsx
  src/components/Transaction/Transaction.module.scss
  src/components/Transaction/TransactionHistory.tsx
  src/components/layouts/AdminLayout/AdminLayout.module.scss
  src/components/layouts/AdminLayout/AdminLayout.tsx
  src/components/layouts/SellerLayout/SellerLayout.module.scss
  src/components/layouts/SellerLayout/SellerLayout.tsx
  src/pages/AdminTransactionPage/AdminTransactionPage.tsx
  src/pages/SellerReportPage/SellerReportPage.module.scss
  src/pages/SellerReportPage/SellerReportPage.tsx
  src/redux/reducers/userSlice.ts
  src/service/AdminService.ts
  src/service/AxiosInstance.tsx
  src/service/SellerService.ts
  src/service/TransactionService.ts
Labels: feature, Bugfix

#80 fix: fix ui at report page for seller
  src/components/Charts/PieChart.css
  src/components/Charts/PieChart.tsx
  src/components/DetailsProperty/DetailsProperty.tsx
  src/components/Map/MapReport.tsx
  src/components/Properties/PropertyCard.tsx
  src/pages/AdminDashboardPage/AdminDashboardPage.tsx
  src/pages/SellerReportPage/SellerReportPage.module.scss
  src/pages/SellerReportPage/SellerReportPage.tsx
  tailwind.config.js
Labels: Bugfix

#79 feat: update admin report page
  src/components/Charts/PieChart.tsx
  src/components/MenuBar/MenuBar.tsx
  src/components/ProgressCard/BalanceViewer.tsx
  src/components/SearchBar/SearchComponent.tsx
  src/components/TableSeller/TableSeller.tsx
  src/components/TableUser/TableUser.tsx
  src/components/Transaction/TransactionHistory.tsx
  src/components/layouts/SellerLayout/SellerLayout.tsx
  src/configs/route.config/route.configs.tsx
  src/pages/AdminDashboardPage/AdminDashboardPage.module.scss
  src/pages/AdminDashboardPage/AdminDashboardPage.tsx
  src/service/AdminService.ts
Labels: feature

#84 fix: seller report
  src/components/Charts/PieChart.tsx
  src/components/ConversionRate/ConversionRateComponent.tsx
  src/components/Profile/UserProfile.module.scss
  src/components/Profile/UserProfile.tsx
  src/components/ProgressCard/BalanceViewer.module.scss
  src/components/ProgressCard/BalanceViewer.tsx
  src/components/SearchBar/SearchComponent.tsx
  src/components/TableProperty/TableProperty.module.scss
  src/components/TableProperty/TableProperty.tsx
  src/components/TableProperty/TablePropertyAdmin.tsx
  src/components/TableSeller/TableSeller.module.scss
  src/components/TableSeller/TableSeller.tsx
  src/components/TableTransaction/TableServiceTransaction.tsx
  src/components/TableTransaction/TableTransaction.module.scss
  src/components/TableTransaction/TableTransaction.tsx
  src/components/TableUser/TableUser.module.scss
  src/components/TableUser/TableUser.tsx
  src/components/Transaction/CreditComponent.tsx
  src/components/Transaction/Transaction.module.scss
  src/components/Transaction/TransactionHistory.tsx
  src/components/layouts/SellerLayout/SellerLayout.tsx
  src/configs/route.config/route.configs.tsx
  src/pages/AdminManageUserPage/AdminManageUserPage.tsx
  src/pages/SellerDashboardPage/SellerDashboardPage.tsx
  src/pages/SellerPage/SellerPage.tsx
  src/pages/SellerReportPage/SellerReportPage.tsx
  src/service/SearchService.ts
  src/service/SellerService.ts
Labels: Bugfix

#87 feat: update home page style
  .gitignore
  src/components/ContactUs/ContactUs.module.scss
  src/components/ContactUs/ContactUs.tsx
  src/components/FeaturedProperties/FeaturedProperties.tsx
  src/components/FeaturedProperties/styles.module.scss
  src/components/Map/Map.module.scss
  src/components/Map/Map.tsx
  src/components/MenuBar/MenuBar.module.scss
  src/components/MenuBar/MenuBar.tsx
  src/components/Properties/PropertyCard.tsx
  src/components/Properties/styles.module.scss
  src/components/SearchBar/TextSearchBar.module.scss
  src/components/Slideshow/SlideShow.module.scss
  src/components/Slideshow/SlideShow.tsx
  src/components/Transaction/TransactionHistory.tsx
  src/pages/DetailPage/DetailPage.module.scss
  src/pages/DetailPage/DetailPage.tsx
Labels: enhancement

#88 feat: update admin dashboard
  src/components/Charts/BarChart.tsx
  src/components/Map/MapProperties.tsx
  src/components/ProgressCard/BalanceViewer.tsx
  src/components/Transaction/TransactionHistory.tsx
  src/pages/AdminDashboardPage/AdminDashboardPage.module.scss
  src/pages/AdminDashboardPage/AdminDashboardPage.tsx
  src/pages/AdminReportPage/AdminReportPage.tsx
  src/utils/commonFunctions.ts
Labels: feature

#89 feat: update seller and admin dashboard style
  src/components/Footer/Footer.tsx
  src/components/Footer/styles.module.scss
  src/components/Transaction/TransactionHistory.tsx
  src/pages/AdminDashboardPage/AdminDashboardPage.tsx
  src/pages/AdminReportPage/AdminReportPage.tsx
  src/pages/SellerDashboardPage/SellerDashboardPage.tsx
  src/pages/SellerReportPage/SellerReportPage.tsx
Labels: enhancement

#91 feat: add donut chart to show properties by category and feature
  src/components/Charts/DonutChart.tsx
  src/components/MenuBar/CollapseMenuItem.tsx
  src/components/MenuBar/MenuBar.tsx
  src/components/TableSeller/TableSeller.tsx
  src/configs/route.config/route.configs.tsx
  src/pages/AdminReportPage/AdminReportPage.tsx
  src/service/AdminService.ts
  src/service/PropertyService.ts
Labels: feature

#90 feat: customize cluster marker to show properties
  src/components/FeaturedProperties/FeaturedProperties.tsx
  src/components/Login/Login.tsx
  src/components/Map/MapProperties.module.scss
  src/components/Map/MapProperties.tsx
  src/components/ProgressCard/BalanceViewer.module.scss
  src/components/ProgressCard/BalanceViewer.tsx
  src/components/Properties/PropertyCard.tsx
  src/components/TableProperty/TableProperty.tsx
  src/components/layouts/AdminLayout/AdminLayout.module.scss
  src/components/layouts/AdminLayout/AdminLayout.tsx
  src/pages/AdminDashboardPage/AdminDashboardPage.module.scss
  src/pages/AdminDashboardPage/AdminDashboardPage.tsx
  src/pages/HomePage/HomePage.tsx
  src/redux/reducers/homeSlice.ts
  src/service/PropertyService.ts
  src/types/properties.ts
  src/types/propertyMarkerMap.ts
Labels: enhancement

#94 fix: change api get max price at admin manage property
  src/components/ModalAdminDeposits/ModalAdminDepositsMain.tsx
  src/components/TableProperty/TablePropertyAdmin.tsx
  src/components/TableSeller/TableSeller.tsx
Labels: Bugfix

#95 fix: change logo and title site
  public/favicon.ico
  public/favicon1.ico
  public/favicon2.ico
  public/index.html
  src/pages/AdminReportPage/AdminReportPage.tsx
  src/pages/HomePage/HomePage.tsx
Labels: Bugfix

#96 fix: responsiveness for about us page
  src/components/BannerWelcome/BannerWelcome.module.scss
  src/components/Charts/DoubleLineChart.tsx
  src/components/Register/Register.tsx
  src/components/SearchBar/SearchComponent.tsx
  src/components/TableProperty/TablePropertyAdmin.tsx
  src/pages/AboutUsPage/AboutUsPage.tsx
Labels: Bugfix

#97 fix: responsiveness for about us page
  src/components/BannerWelcome/BannerWelcome.module.scss
  src/components/BannerWelcome/BannerWelcome.tsx
  src/components/ChangePassword/ChangePassword.tsx
  src/components/Maintenance/MaintenanceComponent.tsx
  src/components/Profile/UserProfile.module.scss
  src/components/Profile/UserProfile.tsx
  src/pages/AboutUsPage/AboutUsPage.tsx
Labels: Bugfix

#98 fix: upgrade to seller
  src/components/Login/Login.tsx
  src/components/MenuBar/MenuBar.tsx
  src/components/ModalAdminDeposits/ModalAdminDepositsMain.tsx
  src/components/Transaction/CreditComponent.tsx
  src/components/UpgradeSeller/UpgradeSeller.tsx
  src/pages/AboutUsPage/AboutUsPage.tsx
  src/pages/SellerDashboardPage/SellerDashboardPage.tsx
  src/pages/SellerPage/SellerPage.tsx
Labels: Bugfix

#99 fix: css for vertical menu bar
  src/components/Drawers/Drawers.module.scss
  src/components/Drawers/Drawers.tsx
  src/components/Login/Login.tsx
  src/components/MenuBar/CollapseMenuItem.tsx
  src/components/MenuBar/MenuBar.module.scss
  src/components/MenuBar/MenuBar.tsx
  src/components/Profile/UserProfile.tsx
  src/components/UpgradeSeller/UpgradeSeller.tsx
  src/pages/FeedbackPage/FeedbackPage.tsx
Labels: Bugfix

#100 fix: conversion rate during maintenance
  src/components/ConversionRate/ConversionRateComponent.tsx
Labels: documentation, Bugfix
